[package]
name = "bevy-ecs-ui-experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.10", default-features = false, features = ["bevy_ui", "bevy_text", "bevy_render", "bevy_asset"]}
bevy_ecss = "0.3"
bevy_common_assets = { version = "0.6", features = ["xml"]}
serde = { version = "1", features = ["derive"]}
tuple_utils = "*"
quick-xml = { version = "0.28", features = ["serialize"]}

[dev-dependencies]

bevy = { version = "0.10", default-features = true}
bevy-inspector-egui = "*"