[package]
name = "bevy-ecs-ui-experiment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9", default-features = false, features = []}
tuple_utils = "*"

[dev-dependencies]

bevy = { version = "0.9", default-features = true}